/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Time since claim is based on month & year collected.Time since claim = Renewal Effective Year & Month  -  Year & Month of claim
 */
export class CalimsHistory extends SpeakeasyBase {
    /**
     * In the last 3 years, has anyone to be covered made any claim under a landlord insurance policy?
     */
    @SpeakeasyMetadata()
    @Expose({ name: "perilLastthreeyrs" })
    perilLastthreeyrs?: number;

    /**
     * In the last year, has anyone to be covered made any claim under a landlord insurance policy?
     */
    @SpeakeasyMetadata()
    @Expose({ name: "perillastyear" })
    perillastyear?: number;
}
