/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { CalimsHistory } from "./calimshistory";
import { PolicyHolder } from "./policyholder";
import { PropertyDetails } from "./propertydetails";
import { Expose, Type } from "class-transformer";

export class Price extends SpeakeasyBase {
    /**
     * Time since claim is based on month & year collected.Time since claim = Renewal Effective Year & Month  -  Year & Month of claim
     */
    @SpeakeasyMetadata()
    @Expose({ name: "calimsHistory" })
    @Type(() => CalimsHistory)
    calimsHistory?: CalimsHistory;

    @SpeakeasyMetadata({ elemType: PolicyHolder })
    @Expose({ name: "policyHolders" })
    @Type(() => PolicyHolder)
    policyHolders?: PolicyHolder[];

    @SpeakeasyMetadata()
    @Expose({ name: "propertyAddress" })
    @Type(() => Address)
    propertyAddress?: Address;

    @SpeakeasyMetadata()
    @Expose({ name: "propertyDetails" })
    @Type(() => PropertyDetails)
    propertyDetails?: PropertyDetails;
}
