/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PropertyDetailsProduct {
    Home = "Home",
    Landlord = "Landlord",
    MyContents = "MyContents",
}

export class PropertyDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "buildingAge" })
    buildingAge?: number;

    /**
     * example: 2010
     */
    @SpeakeasyMetadata()
    @Expose({ name: "builtYear" })
    builtYear: number;

    @SpeakeasyMetadata()
    @Expose({ name: "campaginCode" })
    campaginCode?: string;

    /**
     * If dwelling type = Freestanding house, and defaults to Building Only  OR If dwelling type = Townhouse or villa/Semi detached, duplex or terrace/ Triplex or fourplex, AND strata title = NO, and defaults to Building Only OR If dwelling type = Unit, flat or apartment AND If dwelling type = Townhouse or villa /Semi detached, duplex or terrace/ Triplex or fourplex, AND strata title = YES, and defaults to Contents Only
     */
    @SpeakeasyMetadata()
    @Expose({ name: "coverageType" })
    coverageType: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "dwellingType" })
    dwellingType: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "loggingId" })
    loggingId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "numberOfStoreys" })
    numberOfStoreys?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "occupancyType" })
    occupancyType: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "partner" })
    partner: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product" })
    product: PropertyDetailsProduct[];

    @SpeakeasyMetadata()
    @Expose({ name: "roofType" })
    roofType?: string[];

    /**
     * Risk location
     */
    @SpeakeasyMetadata()
    @Expose({ name: "starteOrTerritory" })
    starteOrTerritory?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "strataTitle" })
    strataTitle?: boolean;

    /**
     * Which of these outbuildings and other features does the property have?
     */
    @SpeakeasyMetadata()
    @Expose({ name: "swimmingPool" })
    swimmingPool?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "wallType" })
    wallType?: string[];
}
